### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by alexandrtovmach** [AndrewKaenko/CV#1]
1. Real size of `main`is not match with A4 format, because you are not included padding to it [ref](https://github.com/AndrewKaenko/CV/blob/main/lib/css/style.css#L13-L16). To fix that please use `calc(210mm - 30px * 2)`.
2. Adding drawbacks it's good but not required, because we're gonna use PostCSS compilers, to do this automatically + based on [caniuse.com report](https://caniuse.com/css-boxshadow) – "box-shadow" property supported by all flagman browsers. [ref](https://github.com/AndrewKaenko/CV/blob/main/lib/css/style.css#L18-L19)
3. Good practice to add comments [like this](https://github.com/AndrewKaenko/CV/blob/main/lib/css/style.css#L101) 👏👏👏
4. I think ["width"](https://github.com/AndrewKaenko/CV/blob/main/lib/css/style.css#L104) (in that case) can be simply replaced with "flex-grow: 1"
5. 🙅‍♂️ NEVER USE 🙅‍♂️ [inline styles](https://github.com/AndrewKaenko/CV/blob/main/index.html#L131) if it's not something not avoidable!

**Comment by AndrewKaenko** [comment]
Fixed bugs
